name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate Sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url: 'https://shadeydo.github.io'

    - name: Commit and push the sitemap
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Automated sitemap generation'
        file_pattern: 'sitemap.xml'